#!/bin/bash
ls -1a | awk 'BEGIN { FS="/"; OFS="/" } { if ($NF == "." || $NF == "..") print $NF; else if (NF > 1) print $NF "/"; else print $NF }' | LC_ALL=C sort -d -f -k1.1,1.1 -k1.2n -k1.3n -k1.4n | paste -sd ","
